### PR TITLE
Reference fixes

### PR DESCRIPTION
**Pull request by aeonic-dev**
This PR fixes references to `Minecraft#getInstance` in common code with a full rewrite of `PlayerEventHandlers` (now `ClientTickEventHandlers`), using static methods and the `@EventBusSubscriber` notation to ensure it's only loaded on the client. We also move config checks for ActionTypes to the `ActionType` class for simplicity and replace the previously static config values with instance fields.

Sponsored (unexpectedly) by the [Modding Inquisition](https://github.com/TheModdingInquisition).

### CODE REVIEW

**Review by Matyrobbrt — APPROVED** [review]

**Comment by ianwijma** [comment]
Thank you 2 so much for this PR @Matyrobbrt and @aeonic-dev! I will review and merge this PR tonight or tomorrow before I start working on the 1.19 upgrade. 

Again, thank you 2 so much!

**Comment by aeonic-dev** [comment]
Great to hear from you!
No problem, we're happy to help. Thank you for your work and for keeping this mod open source!

**Review by ianwijma — APPROVED** [review]
I'm not a Java developer and learned a TONE from this. Thanks a lot for this PR! It's so much more stream lined.

**Comment by aeonic-dev** [comment]
Happy to help man! I do have a few other changes I want to make that I took note of, but to make your job easier I'll wait till there's a more solid 1.19 branch before I make another PR. Thanks again for your work!

**Pull request merged**
